# Generated by Django 4.1.7 on 2023-03-11 17:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rich_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
