# Generated by Django 4.1.7 on 2023-03-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_rich_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rich_title',
        ),
    ]
